modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/iMoonDay/PersonalCloudStorage/issues"
license = "MIT"

[[mods]]
modId = "personalcloudstorage"
version = "${version}"
displayName = "Personal Cloud Storage"
authors = "iMoonDay"
description = '''
Create your own personal cloud storage with endless expansion and seamless item management
'''
logoFile = "assets/personalcloudstorage/icon.png"

[[dependencies.personalcloudstorage]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.personalcloudstorage]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
